"""Shared real-browser regression checks for the ribbon and semantic control additions."""
def run_workspace_checks(page, check, require):
    page.evaluate("window.savedWorkspace=structuredClone(studio.engine.document)")
    def fixture():
        page.evaluate("async()=>{const D=studio.Drawing,d=D.createDocument('Workspace qualification');d.pages[0].id='features';d.pages[0].width=1000;d.pages[0].height=600;d.pages[0].shapes=[D.createShape('rectangle',{id:'feature-a',x:130,y:150,width:180,height:90,text:'Review request',data:{progress:55}}),D.createShape('roundRect',{id:'feature-b',x:540,y:150,width:180,height:90,text:'Approve request'})];await studio.replace(d);studio.engine.select(['feature-a']);studio.workspace.setTab('home');studio.workspace.setPane('format');}")
        page.wait_for_timeout(60)
    fixture()
    def ribbons():
        require(page.locator('[data-tab]').count()==8)
        page.locator('[data-tab="home"]').focus();page.keyboard.press('ArrowRight')
        require(page.locator('[data-tab="insert"]').get_attribute('aria-selected')=='true')
        require(page.locator('#ribbon-insert').is_visible())
        page.keyboard.press('End');require(page.locator('#ribbon-developer').is_visible())
        page.keyboard.press('Home');require(page.locator('#ribbon-home').is_visible())
    check('ribbon tabs implement keyboard roving focus and real panels',ribbons)
    def file_view():
        page.locator('[data-action="file"]').click();require(page.locator('#backstage').is_visible())
        require(page.locator('#format option').count()==8)
        page.locator('[data-action="close-file"]').click();require(not page.locator('#backstage').is_visible())
    check('Backstage exposes explicit export profiles',file_view)
    def container():
        page.evaluate("studio.engine.select(['feature-a','feature-b'])")
        page.locator('[data-tab="insert"]').click();page.locator('[data-action="container"]').click()
        page.get_by_label('Container title',exact=True).fill('Approval group')
        page.locator('#workspace-dialog').get_by_role('button',name='Apply',exact=True).click()
        page.wait_for_function("studio.engine.allShapes().some(s=>s.text==='Approval group')")
        require(page.evaluate("studio.engine.getShape(studio.engine.selection[0]).container.memberIds.length===2"))
        page.evaluate("window.containerId=studio.engine.selection[0]")
    check('ribbon creates a real semantic container around selection',container)
    def member_drag():
        page.evaluate("studio.control.fit();studio.engine.select([containerId]);window.beforeMove=studio.engine.getShape('feature-a').x")
        xy=page.evaluate("()=>{const s=studio.engine.getShape(containerId);return studio.control.worldToScreen({x:s.x+s.width/2,y:s.y+15})}")
        box=page.locator('#drawing canvas').bounding_box();x,y=box['x']+xy['x'],box['y']+xy['y']
        page.mouse.move(x,y);page.mouse.down();page.mouse.move(x+42,y+20,steps=5);page.mouse.up()
        require(page.evaluate("studio.engine.getShape('feature-a').x>beforeMove"))
        page.locator('#undo').click();require(page.evaluate("studio.engine.getShape('feature-a').x===beforeMove"))
    check('container header drag moves contents in one undo entry',member_drag)
    def clipboard():
        page.evaluate("studio.workspace.setTab('home');studio.engine.select([containerId])")
        page.locator('[data-action="copy"]').click();page.locator('[data-action="paste"]').click()
        page.wait_for_function("studio.engine.allShapes().filter(s=>s.container).length===2")
        require(page.evaluate("studio.engine.allShapes().length===6"))
        page.locator('#undo').click();require(page.evaluate("studio.engine.allShapes().length===3"))
    check('ribbon clipboard remaps container and member identities',clipboard)
    def comments():
        page.evaluate("studio.engine.select(['feature-a'])")
        page.locator('[data-tab="review"]').click();page.locator('#ribbon-review [data-action="comment"]').click()
        page.get_by_label('Comment',exact=True).fill('Check approval semantics')
        page.locator('#workspace-dialog').get_by_role('button',name='Post comment',exact=True).click()
        page.wait_for_function("studio.engine.document.comments?.length===1")
        page.locator('.comment-actions').get_by_role('button',name='Reply',exact=True).click()
        page.get_by_label('Reply',exact=True).fill('Verified')
        page.locator('#workspace-dialog').get_by_role('button',name='Post reply',exact=True).click()
        page.wait_for_function("studio.engine.document.comments[0].replies.length===1")
        page.locator('.comment-actions').get_by_role('button',name='Resolve',exact=True).click()
        page.wait_for_function("studio.engine.document.comments[0].resolved")
        page.locator('#include-resolved').check();require(page.locator('.comment-card.resolved').count()==1)
    check('review pane posts replies and resolves comments',comments)
    def sheet():
        page.locator('[data-tab="developer"]').click();page.locator('[data-action="pane-sheet"]').click()
        page.locator('#sheet-name').fill('Width');page.locator('#sheet-value').fill('=3 in')
        page.locator('#sheet-edit button').click();page.wait_for_function("studio.engine.getShape('feature-a').width===288")
        page.locator('#undo').click();require(page.evaluate("studio.engine.getShape('feature-a').width===180"))
        page.evaluate('studio.sheet.deactivate()')
    check('ShapeSheet pane evaluates units and participates in undo',sheet)
    def rich_text():
        page.evaluate("studio.engine.update('feature-a',{richText:{paragraphs:[{runs:[{text:'First'}],indent:12,spaceAfter:4},{runs:[{text:'Second'}],bullet:'bullet'}]}});studio.control.editRichText('feature-a')")
        field=page.locator('#drawing [contenteditable="true"]');field.press('Control+b');field.press('Control+Enter')
        require(page.evaluate("()=>{const t=studio.engine.getShape('feature-a').richText;return t.paragraphs.length===2&&t.paragraphs[0].indent===12&&t.paragraphs[0].spaceAfter===4&&t.paragraphs[1].bullet==='bullet'&&t.paragraphs.every(p=>p.runs.every(r=>r.style?.bold))}"))
        page.evaluate("studio.control.editRichText('feature-a')");field.press('Control+a');field.press('Backspace');field.press('Escape')
        require(page.evaluate("studio.engine.getShape('feature-a').text==='First\\nSecond'"))
    check('rich formatting preserves paragraphs and spacing; Escape cancels',rich_text)
    def graphic():
        page.evaluate("studio.workspace.setTab('data');studio.engine.select(['feature-a'])")
        page.locator('[data-action="data-graphics"]').click()
        page.get_by_label('Data field',exact=True).select_option('progress');page.get_by_label('Graphic',exact=True).select_option('bar')
        page.locator('#workspace-dialog').get_by_role('button',name='Apply',exact=True).click()
        page.wait_for_function("!!studio.engine.getShape('feature-a').dataGraphicId")
        require(page.evaluate("studio.Drawing.exportSvg(studio.engine.document).includes('55')"))
        page.evaluate('studio.control.renderer.prepare(studio.control.pageId)')
        require(page.evaluate("studio.control.renderer.getItem('feature-a').rect.height===studio.engine.getShape('feature-a').height"))
    check('data graphics render without changing selection geometry',graphic)
    def guide():
        page.locator('[data-tab="view"]').click();page.locator('[data-action="add-guide"]').click()
        page.get_by_label('Position in CSS pixels',exact=True).fill('240')
        page.locator('#workspace-dialog').get_by_role('button',name='Apply',exact=True).click()
        page.wait_for_function("studio.engine.document.pages[0].guides?.x.includes(240)")
    check('guide dialog adds model-backed ruler guides',guide)
    def command_search():
        page.keyboard.press('Control+k');page.get_by_label('Find a command',exact=True).fill('Validate diagram')
        page.get_by_label('Find a command',exact=True).press('Enter')
        page.wait_for_function("document.getElementById('workspace-dialog-title').textContent==='Diagram validation'")
        page.locator('#workspace-dialog-close').click()
    check('command search executes registered model validation',command_search)
    def image_export():
        require(page.evaluate("async()=>{const D=studio.Drawing,canvas=document.createElement('canvas');canvas.width=canvas.height=8;const ctx=canvas.getContext('2d');ctx.fillStyle='#ff0000';ctx.fillRect(0,0,8,8);studio.engine.add(studio.control.pageId,D.createShape('image',{id:'raster-check',x:700,y:350,width:80,height:80,image:{source:canvas.toDataURL(),fit:'contain',alt:'Red raster'}}));const png=await studio.control.exportPng(1);const bmp=await createImageBitmap(png),out=document.createElement('canvas');out.width=bmp.width;out.height=bmp.height;const c=out.getContext('2d');c.drawImage(bmp,0,0);bmp.close();const pixel=c.getImageData(730,380,1,1).data;return pixel[0]===255&&pixel[1]===0&&pixel[2]===0;}"))
    check('PNG waits for embedded raster decoding and preserves image color',image_export)
    def print_layer():
        require(page.evaluate("async()=>{const e=studio.engine,p=e.getPage(studio.control.pageId);e.updatePage(p.id,{layers:[...p.layers,{id:'nonprint',name:'No print',visible:true,printable:false,locked:false}]});e.update('raster-check',{layerId:'nonprint'});const png=await studio.control.exportPng(1),bmp=await createImageBitmap(png),canvas=document.createElement('canvas');canvas.width=bmp.width;canvas.height=bmp.height;const c=canvas.getContext('2d');c.drawImage(bmp,0,0);bmp.close();const pixel=c.getImageData(730,380,1,1).data;return pixel[0]===255&&pixel[1]===255&&pixel[2]===255;}"))
    check('PNG honors independent nonprinting layer flags',print_layer)
    def templates():
        page.on('dialog',lambda dialog:dialog.accept())
        page.locator('[data-tab="insert"]').click();page.locator('.library [data-action="templates"]').click()
        page.locator('[data-template="swimlanes"]').click();page.wait_for_function("studio.engine.allShapes().some(s=>s.container?.layout==='pool')")
        require(page.evaluate("studio.engine.allShapes().filter(s=>s.kind==='swimlane').length===3"))
    check('template gallery creates usable cross-functional swimlanes',templates)
    page.evaluate('async()=>{await studio.replace(savedWorkspace);studio.workspace.setTab("home");studio.workspace.setPane("format");}')
